##################################################################################################################################
#Deployment file

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: face-rekognition-deployment
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: face-rekognition
  template:
    metadata:
      labels:
        app: face-rekognition
    spec:
      serviceAccountName: face-rekognition-sa
      containers:
      - name: face-rekognition-app
        image: logeshshanmugavel/face-rekognition-app:latest
        ports:
        - containerPort: 81