apiVersion: apps/v1
kind: Deployment
metadata: 
  name: face-rekognition
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: face-rekognition
  template:
    metadata:
      labels:
        app: face-rekognition
    spec:
      containers:
      - name: face-rekognition
        image: face-rekognition:latest
        ports:
        - containerPort: 81