apiVersion: v1
kind: Service
metadata:
  name: face-rekognition-service
spec:
  selector:
    app: face-rekognition
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 81
      targetPort: 81